language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "13"
deploy:
  provider: script
  script: npm install && npm run deploy
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master